# Generated by Django 5.0.6 on 2024-05-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "Account_ID",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("Name", models.CharField(max_length=255)),
                ("Balance", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
